# Generated by Django 4.1.4 on 2023-01-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="school_name",
            field=models.CharField(max_length=30),
        ),
    ]
