# Generated by Django 4.1.4 on 2023-01-10 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_alter_school_school_name"),
    ]

    operations = [
        migrations.DeleteModel(name="school",),
    ]
